# Generated by Django 5.1.1 on 2024-10-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
