# Generated by Django 5.1.1 on 2024-10-08 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_customuser_date_of_birth_customuser_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='last_nme',
            new_name='last_name',
        ),
    ]
