# Generated by Django 5.1.1 on 2024-10-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_rename_last_nme_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
