# Generated by Django 5.1.1 on 2024-10-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_otp_rename_first_name_customuser_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Otp',
        ),
        migrations.DeleteModel(
            name='CustomProfile',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
