# Generated by Django 5.1.1 on 2024-10-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
